# This is a sample build configuration for C++ ? Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ubuntu:14.04

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - sudo apt-get update && apt-get install -y gcc make bison libreadline-dev gawk libtool realpath pkg-config zlibc gnulib libcap-dev rsync busybox curl wget squashfs-tools flex python perl zip unzip tcl bzip2 locales git xsltproc bc subversion
          - sudo locale-gen en_US.UTF-8
          - make package-atom
          - make package-arm
          - make
